### PR TITLE
fix duplicate constant from libspirv.h

### PR DESCRIPTION
**Pull request by Sirox0**
in libspirv.h is defined a constant `kDefaultMaxIdBound`. defining constants in headers is a bad practice, as it causes duplicate symbols if you include it in more than 1 compilation unit.

better solution, that will not cause this issue, would be to make it a compile-time macro.

### CODE REVIEW

**Comment by s-perron** [comment]
Sorry I didn't reply earlier. I had looked at it. Using a macro means it is no longer namespaced. We discussed other ideas. We want it to have a weak definition. I didn't test, but what happens if you make it constexpr. I wanted to test it, but forgot? If that does not work, just make it static.

**Comment by Sirox0** [comment]
libspirv.h is C-compatibile header, but constexpr only exists in C++. so, to not break this compatibility, i propose making it static.
i edited the pr.

**Review by s-perron — APPROVED** [review]
