### ISSUE TITLE
SPRIV-Tools doesn't compile with GCC 8.1

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/SPIRV-Tools#1541]
[build.log](https://github.com/KhronosGroup/SPIRV-Tools/files/1970660/build.log)

/var/tmp/portage/dev-util/spirv-tools-9999/work/spirv-tools-9999/source/text_handler.cpp: In member function ‘spv_result_t libspirv::AssemblyContext::binaryEncodeString(const char*, spv_instruction_t*)’:
/var/tmp/portage/dev-util/spirv-tools-9999/work/spirv-tools-9999/source/text_handler.cpp:316:10: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   strncpy(dest, value, length);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/dev-util/spirv-tools-9999/work/spirv-tools-9999/source/text_handler.cpp:298:31: note: length computed here
   const size_t length = strlen(value);
                         ~~~~~~^~~~~~~

**Comment by karolherbst** [comment]
Already happens with GCC 8.0

**Comment by karolherbst** [comment]
'cmake -DSPIRV_WERROR=OFF' should be a valid workaround to get it built though.

**Comment by acidYeah** [comment]
What is the status of this issue? Are there any updates, or other closed issues you know of that solved the problem?

**Comment by s-perron** [comment]
I tried out gcc version 8.0.1.  I did not see the failure reported here.  I did find another error in HexFloat that I fixed up.  I'll see if I can install 8.1.

**Comment by s-perron** [comment]
I was able to reproduce this today.  I was doing a debug build, but it only shows up in a release build.
