### ISSUE TITLE
current gate tip fails to build with mingw64 gcc 10.1.0 due to maybe uninitialized error

### ISSUE THREAD

**Issue by binarycrusader** [KhronosGroup/SPIRV-Tools#3526]
Current spirv-tools gate tip fails to build with mingw64 gcc 10.0 due to maybe uninitialized error:

```
In file included from G:/Devel/scopes-md/SPIRV-Tools/test/opt/instruction_test.cpp:21:
G:/Devel/scopes-md/SPIRV-Tools/source/opt/instruction.h: In member function 'virtual void spvtools::opt::{anonymous}::InstructionTest_OperandAsLiteralUint64_64bits_Test::TestBody()':
G:/Devel/scopes-md/SPIRV-Tools/source/opt/instruction.h:101:23: error: '*((void*)& operand +32)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                        101 |     uint64_t result = uint64_t(words[0]);
                            |                       ^~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [test/opt/CMakeFiles/test_opt.dir/build.make:629: test/opt/CMakeFiles/test_opt.dir/instruction_test.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2656: test/opt/CMakeFiles/test_opt.dir/all] Error 2
make: *** [Makefile:161: all] Error 2 
```

**Comment by binarycrusader** [comment]
Looks like this only happens when the optional googletest component is checked out per the build instructions:

`git clone https://github.com/google/googletest.git external/googletest # optional`

**Comment by dneto0** [comment]
The normal development flow is to have googletest checked out and to build and run tests. So this is intended to build without issue.

The method in question is:
  // Returns a literal integer operand as a uint64_t
  uint64_t AsLiteralUint64() const {
    assert(type == SPV_OPERAND_TYPE_TYPED_LITERAL_NUMBER);
    assert(1 <= words.size());
    assert(words.size() <= 2);
    // Load the low word.
    uint64_t result = uint64_t(words[0]);
    if (words.size() > 1) {
      result = result | (uint64_t(words[1]) << 32);
    }
    return result;
  }

The data is protected by contract, but the compiler can't tell that.  And in a debug build the bad case would trigger the assert.
It would be harmless to add a member initializations.  I can try that.

**Comment by dneto0** [comment]
Hey @binarycrusader can you see if https://github.com/KhronosGroup/SPIRV-Tools/pull/3556 fixes the problem for you?
I don't have MinGW GCC 10 and it's not readily available to me.

**Comment by binarycrusader** [comment]
@dneto0 No, but that's not surprising.  The compiler is sophisticated enough to know that words might be empty(), so words[0] could access uninitialized memory.

A proper bounds check eliminates the warning:

```c++
  // Returns a literal integer operand as a uint64_t
  uint64_t AsLiteralUint64() const {
    // ...
    // Load the low word.
    if (words.empty()) {
        return 0;
    }
```

I know that's possibly undesirable from a perf standpoint, but unless a pragma or some other trick is used to suppress the warning or trick the compiler, I don't see a way around it.

For what it's worth, there are quite a few open bugs around gcc's uninitialized warnings, so this particular compiler check isn't viewed as wholly reliable:

https://gcc.gnu.org/bugzilla/buglist.cgi?quicksearch=may%20be%20uninitialized

If there's a desire to keep the code as-is, disabling the warning is probably the safest option.

**Comment by s-perron** [comment]
It is strange that it only does this when the tests are enabled.  I wonder if this has to do with how it is used in a test, and not a general usage.

**Comment by s-perron** [comment]
This has been fixed.
