### ISSUE TITLE
Build of 2021.2 (with SPIRV-Headers 1.5.4.raytracing.fixed) fails with 

### ISSUE THREAD

**Issue by paulmenzel** [KhronosGroup/SPIRV-Tools#4441]
[Same issue as issue https://github.com/KhronosGroup/SPIRV-Tools/issues/3647, which was closed though.]

```
[ 40%] Building CXX object source/CMakeFiles/SPIRV-Tools-static.dir/val/validate_layout.cpp.o
cd /dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/build/source && /usr/bin/c++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source -I/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/include -I/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/build -I/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/external/spirv-headers/include  -g -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -o CMakeFiles/SPIRV-Tools-static.dir/val/validate_layout.cpp.o -c /dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/val/validate_layout.cpp
/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/opcode.cpp: In function ‘bool spvOpcodeIsAtomicWithLoad(SpvOp)’:
/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/opcode.cpp:420:10: error: ‘SpvOpAtomicFMinEXT’ was not declared in this scope
     case SpvOpAtomicFMinEXT:
          ^~~~~~~~~~~~~~~~~~
/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/opcode.cpp:420:10: note: suggested alternative: ‘SpvOpAtomicFAddEXT’
     case SpvOpAtomicFMinEXT:
          ^~~~~~~~~~~~~~~~~~
          SpvOpAtomicFAddEXT
/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/opcode.cpp:423:10: error: ‘SpvOpAtomicFMaxEXT’ was not declared in this scope
     case SpvOpAtomicFMaxEXT:
          ^~~~~~~~~~~~~~~~~~
/dev/shm/bee-pmenzel/spirv-tools/spirv-tools-2021.2-0/source/source/opcode.cpp:423:10: note: suggested alternative: ‘SpvOpAtomicFAddEXT’
     case SpvOpAtomicFMaxEXT:
          ^~~~~~~~~~~~~~~~~~
          SpvOpAtomicFAddEXT
```

**Comment by paulmenzel** [comment]
Version 2020.6 builds fine with SPIRV-Headers 1.5.4.raytracing.fixed.

**Comment by jdknight** [comment]
The constants `SpvOpAtomicFMinEXT`/`SpvOpAtomicFMaxEXT` look to have been introduced in KhronosGroup/SPIRV-Headers@25fd8d031bbb88d46f28a8be4aea9456e59cba9b, which has not been tagged in that repository.

I would recommend to consult the revision of "SPIRV-Headers" referenced inside  [`DEPS`](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/DEPS) to see which header revision is required for the reference/tag of "SPIRV-Tools" being used. For example, `v2021.2` appears to require [`07f259e68af3a540038fa32df522554e74f53ed5`](https://github.com/KhronosGroup/SPIRV-Tools/blob/v2021.2/DEPS#L9) of "SPIRV-Headers".

**Comment by paulmenzel** [comment]
Thank you for the analysis. So, release 2021.2 requires/depends on SPIRV-Headers with no release.

    $ git describe 07f259e68af3a540038fa32df522554e74f53ed5
    1.5.4.raytracing.fixed-71-g07f259e
    $ git tag --contains 07f259e68af3a540038fa32df522554e74f53ed5
    

I created issue https://github.com/KhronosGroup/SPIRV-Headers/issues/234 in SPIRV-Headers.

**Comment by s-perron** [comment]
There release is expected to build with the spirv-header revision referenced in the DEPS file. No guarantee for any other revision.
